// swift-tools-version: 5.7
// AUTO-GENERATED — do not hand-edit `Package.swift` at the repo root.
// Edit this template (`.github/swiftpm-template/Package.swift.in`) and
// changes propagate to `Package.swift` at the repo root via the next
// `publish-swiftpm` workflow run, which also re-points the release tag
// to the resulting commit so SPM consumers using `from: "X.Y.Z"` always
// resolve to a `Package.swift` with matching URL + checksum.

import PackageDescription

let version = "0.4.0"

let package = Package(
    name: "PqcCore",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "PqcCore", targets: ["PqcCore"])
    ],
    targets: [
        // PqcCore-X.Y.Z.xcframework.zip is a slim archive — just the
        // .xcframework, no other top-level entries — which is what
        // Apple's "Distributing Binary Frameworks as Swift Packages"
        // doc shows. CocoaPods uses a separate (fat) zip with the same
        // xcframework + pqc.swift + LICENSE; both zips are produced by
        // the same release workflow.
        //
        // The binaryTarget name MUST match the xcframework's modulemap
        // module name ("pqcFFI" — declared in module.modulemap). When
        // they diverge, consumers can hit "no such module pqcFFI" at
        // build time even though SPM resolved the binaryTarget fine,
        // because the modulemap's name is what the Swift compiler sees.
        .binaryTarget(
            name: "pqcFFI",
            url: "https://github.com/sriharsha-y/pqc-mobile-client/releases/download/v\(version)/PqcCore-\(version).xcframework.zip",
            checksum: "6b26f292d7d2721e3e0f03d4721da356ff5d1db7f2fc20567fafacf5af7773df"
        ),
        // Swift binding generated by UniFFI; lives under Sources/PqcCore
        // at the repo root, refreshed by `publish-swiftpm` on each
        // release (extracted from the fat zip). pqc.swift contains
        // `import pqcFFI` which matches both the xcframework modulemap
        // and the binaryTarget name above.
        .target(
            name: "PqcCore",
            dependencies: ["pqcFFI"],
            path: "Sources/PqcCore"
        )
    ]
)
