// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pqcFFI)
import pqcFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pqc_client_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pqc_client_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePqcClientInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * The HTTPS client exposed to Kotlin / Swift via UniFFI.
 *
 * Holds a single `reqwest::Client` with PQC TLS configured. Construct once
 * per process (it owns the connection pool); calling `request` is cheap.
 */
public protocol PqcHttpClientProtocol: AnyObject, Sendable {
    
    func request(req: HttpRequest) async throws  -> HttpResponse
    
}
/**
 * The HTTPS client exposed to Kotlin / Swift via UniFFI.
 *
 * Holds a single `reqwest::Client` with PQC TLS configured. Construct once
 * per process (it owns the connection pool); calling `request` is cheap.
 */
open class PqcHttpClient: PqcHttpClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pqc_client_fn_clone_pqchttpclient(self.pointer, $0) }
    }
    /**
     * Returns `PqcError` (not panic) so consumers surface bad config —
     * e.g. malformed base64 in pinned_cert_sha256 — as a typed error.
     */
public convenience init(config: PqcConfig)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypePqcError_lift) {
    uniffi_pqc_client_fn_constructor_pqchttpclient_new(
        FfiConverterTypePqcConfig_lower(config),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pqc_client_fn_free_pqchttpclient(pointer, $0) }
    }

    

    
open func request(req: HttpRequest)async throws  -> HttpResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pqc_client_fn_method_pqchttpclient_request(
                    self.uniffiClonePointer(),
                    FfiConverterTypeHttpRequest_lower(req)
                )
            },
            pollFunc: ffi_pqc_client_rust_future_poll_rust_buffer,
            completeFunc: ffi_pqc_client_rust_future_complete_rust_buffer,
            freeFunc: ffi_pqc_client_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeHttpResponse_lift,
            errorHandler: FfiConverterTypePqcError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePqcHttpClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PqcHttpClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PqcHttpClient {
        return PqcHttpClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PqcHttpClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PqcHttpClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PqcHttpClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcHttpClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> PqcHttpClient {
    return try FfiConverterTypePqcHttpClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcHttpClient_lower(_ value: PqcHttpClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypePqcHttpClient.lower(value)
}




public struct HttpRequest {
    public var method: HttpMethod
    public var url: String
    public var headers: [String: [String]]
    public var body: Data?
    public var timeoutMs: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(method: HttpMethod, url: String, headers: [String: [String]], body: Data?, timeoutMs: UInt64?) {
        self.method = method
        self.url = url
        self.headers = headers
        self.body = body
        self.timeoutMs = timeoutMs
    }
}

#if compiler(>=6)
extension HttpRequest: Sendable {}
#endif


extension HttpRequest: Equatable, Hashable {
    public static func ==(lhs: HttpRequest, rhs: HttpRequest) -> Bool {
        if lhs.method != rhs.method {
            return false
        }
        if lhs.url != rhs.url {
            return false
        }
        if lhs.headers != rhs.headers {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        if lhs.timeoutMs != rhs.timeoutMs {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(method)
        hasher.combine(url)
        hasher.combine(headers)
        hasher.combine(body)
        hasher.combine(timeoutMs)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpRequest {
        return
            try HttpRequest(
                method: FfiConverterTypeHttpMethod.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                headers: FfiConverterDictionaryStringSequenceString.read(from: &buf), 
                body: FfiConverterOptionData.read(from: &buf), 
                timeoutMs: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HttpRequest, into buf: inout [UInt8]) {
        FfiConverterTypeHttpMethod.write(value.method, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterDictionaryStringSequenceString.write(value.headers, into: &buf)
        FfiConverterOptionData.write(value.body, into: &buf)
        FfiConverterOptionUInt64.write(value.timeoutMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lift(_ buf: RustBuffer) throws -> HttpRequest {
    return try FfiConverterTypeHttpRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lower(_ value: HttpRequest) -> RustBuffer {
    return FfiConverterTypeHttpRequest.lower(value)
}


public struct HttpResponse {
    public var status: UInt16
    public var headers: [String: [String]]
    public var body: Data
    public var negotiatedProtocol: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(status: UInt16, headers: [String: [String]], body: Data, negotiatedProtocol: String) {
        self.status = status
        self.headers = headers
        self.body = body
        self.negotiatedProtocol = negotiatedProtocol
    }
}

#if compiler(>=6)
extension HttpResponse: Sendable {}
#endif


extension HttpResponse: Equatable, Hashable {
    public static func ==(lhs: HttpResponse, rhs: HttpResponse) -> Bool {
        if lhs.status != rhs.status {
            return false
        }
        if lhs.headers != rhs.headers {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        if lhs.negotiatedProtocol != rhs.negotiatedProtocol {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(status)
        hasher.combine(headers)
        hasher.combine(body)
        hasher.combine(negotiatedProtocol)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpResponse {
        return
            try HttpResponse(
                status: FfiConverterUInt16.read(from: &buf), 
                headers: FfiConverterDictionaryStringSequenceString.read(from: &buf), 
                body: FfiConverterData.read(from: &buf), 
                negotiatedProtocol: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HttpResponse, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.status, into: &buf)
        FfiConverterDictionaryStringSequenceString.write(value.headers, into: &buf)
        FfiConverterData.write(value.body, into: &buf)
        FfiConverterString.write(value.negotiatedProtocol, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpResponse_lift(_ buf: RustBuffer) throws -> HttpResponse {
    return try FfiConverterTypeHttpResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpResponse_lower(_ value: HttpResponse) -> RustBuffer {
    return FfiConverterTypeHttpResponse.lower(value)
}


/**
 * Configuration handed to `PqcHttpClient::new`. Defaults are tuned for
 * mobile and safe to set from Swift/Kotlin without reading the docs.
 * All `*_ms` fields are milliseconds.
 */
public struct PqcConfig {
    /**
     * Base64 SHA-256 of a DER SPKI (standard or URL-safe) the client will
     * accept. Matches if ANY cert in the chain — leaf or intermediate —
     * has a matching SPKI hash (the leaf must still parse); empty disables
     * pinning. Pin the issuing intermediate CA, keep >= 2 pins, never pin a
     * public root. See `src/pinning.rs`.
     */
    public var pinnedCertSha256: [String]
    /**
     * Advertise X25519MLKEM768 (IANA 0x11EC) as the preferred KEX group
     * (default true). The ClientHello also carries classical groups, so a
     * peer that rejects the hybrid falls back to classical — this is a
     * preference, not enforcement. Set false only for A/B comparison.
     */
    public var enablePostQuantum: Bool
    /**
     * Total request budget (handshake + headers + body); on expiry the
     * request aborts with `PqcError::Timeout`. `None` means no total cap —
     * discouraged for mobile.
     */
    public var defaultTimeoutMs: UInt64?
    /**
     * TCP-connect / TLS-handshake budget, capped separately from
     * `default_timeout_ms` so a stalled connect (e.g. cellular handover)
     * fails fast instead of burning the whole request budget. `None` = 10s.
     */
    public var connectTimeoutMs: UInt64?
    /**
     * Hard ceiling on a response body (post-decompression); exceeding it
     * trips `PqcError::InvalidResponse`. Guards against decompression bombs
     * (CWE-409) — gzip/brotli are on, so without a cap a tiny stream can
     * expand to GBs and OOM the app. `None` defaults to 16 MiB.
     */
    public var maxBodyBytes: UInt64?
    /**
     * Off by default: no cookie jar, so callers round-trip
     * `Set-Cookie`/`Cookie` themselves. Auto-attaching cookies across
     * endpoints is a session-leak vector — enable only when needed.
     */
    public var enableCookies: Bool
    /**
     * Sent verbatim as `User-Agent`. `None` uses reqwest's default, which
     * many WAFs (Akamai Bot Manager, bank UA allowlists) reject — set your
     * app's identifier.
     */
    public var userAgent: String?
    /**
     * How to handle 3xx. Default `SameOriginOnly` — cross-origin redirects
     * are refused so a redirect can't silently downgrade to an un-pinned
     * host.
     */
    public var redirectPolicy: RedirectPolicy

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Base64 SHA-256 of a DER SPKI (standard or URL-safe) the client will
         * accept. Matches if ANY cert in the chain — leaf or intermediate —
         * has a matching SPKI hash (the leaf must still parse); empty disables
         * pinning. Pin the issuing intermediate CA, keep >= 2 pins, never pin a
         * public root. See `src/pinning.rs`.
         */pinnedCertSha256: [String], 
        /**
         * Advertise X25519MLKEM768 (IANA 0x11EC) as the preferred KEX group
         * (default true). The ClientHello also carries classical groups, so a
         * peer that rejects the hybrid falls back to classical — this is a
         * preference, not enforcement. Set false only for A/B comparison.
         */enablePostQuantum: Bool = true, 
        /**
         * Total request budget (handshake + headers + body); on expiry the
         * request aborts with `PqcError::Timeout`. `None` means no total cap —
         * discouraged for mobile.
         */defaultTimeoutMs: UInt64?, 
        /**
         * TCP-connect / TLS-handshake budget, capped separately from
         * `default_timeout_ms` so a stalled connect (e.g. cellular handover)
         * fails fast instead of burning the whole request budget. `None` = 10s.
         */connectTimeoutMs: UInt64?, 
        /**
         * Hard ceiling on a response body (post-decompression); exceeding it
         * trips `PqcError::InvalidResponse`. Guards against decompression bombs
         * (CWE-409) — gzip/brotli are on, so without a cap a tiny stream can
         * expand to GBs and OOM the app. `None` defaults to 16 MiB.
         */maxBodyBytes: UInt64?, 
        /**
         * Off by default: no cookie jar, so callers round-trip
         * `Set-Cookie`/`Cookie` themselves. Auto-attaching cookies across
         * endpoints is a session-leak vector — enable only when needed.
         */enableCookies: Bool, 
        /**
         * Sent verbatim as `User-Agent`. `None` uses reqwest's default, which
         * many WAFs (Akamai Bot Manager, bank UA allowlists) reject — set your
         * app's identifier.
         */userAgent: String?, 
        /**
         * How to handle 3xx. Default `SameOriginOnly` — cross-origin redirects
         * are refused so a redirect can't silently downgrade to an un-pinned
         * host.
         */redirectPolicy: RedirectPolicy) {
        self.pinnedCertSha256 = pinnedCertSha256
        self.enablePostQuantum = enablePostQuantum
        self.defaultTimeoutMs = defaultTimeoutMs
        self.connectTimeoutMs = connectTimeoutMs
        self.maxBodyBytes = maxBodyBytes
        self.enableCookies = enableCookies
        self.userAgent = userAgent
        self.redirectPolicy = redirectPolicy
    }
}

#if compiler(>=6)
extension PqcConfig: Sendable {}
#endif


extension PqcConfig: Equatable, Hashable {
    public static func ==(lhs: PqcConfig, rhs: PqcConfig) -> Bool {
        if lhs.pinnedCertSha256 != rhs.pinnedCertSha256 {
            return false
        }
        if lhs.enablePostQuantum != rhs.enablePostQuantum {
            return false
        }
        if lhs.defaultTimeoutMs != rhs.defaultTimeoutMs {
            return false
        }
        if lhs.connectTimeoutMs != rhs.connectTimeoutMs {
            return false
        }
        if lhs.maxBodyBytes != rhs.maxBodyBytes {
            return false
        }
        if lhs.enableCookies != rhs.enableCookies {
            return false
        }
        if lhs.userAgent != rhs.userAgent {
            return false
        }
        if lhs.redirectPolicy != rhs.redirectPolicy {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pinnedCertSha256)
        hasher.combine(enablePostQuantum)
        hasher.combine(defaultTimeoutMs)
        hasher.combine(connectTimeoutMs)
        hasher.combine(maxBodyBytes)
        hasher.combine(enableCookies)
        hasher.combine(userAgent)
        hasher.combine(redirectPolicy)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePqcConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PqcConfig {
        return
            try PqcConfig(
                pinnedCertSha256: FfiConverterSequenceString.read(from: &buf), 
                enablePostQuantum: FfiConverterBool.read(from: &buf), 
                defaultTimeoutMs: FfiConverterOptionUInt64.read(from: &buf), 
                connectTimeoutMs: FfiConverterOptionUInt64.read(from: &buf), 
                maxBodyBytes: FfiConverterOptionUInt64.read(from: &buf), 
                enableCookies: FfiConverterBool.read(from: &buf), 
                userAgent: FfiConverterOptionString.read(from: &buf), 
                redirectPolicy: FfiConverterTypeRedirectPolicy.read(from: &buf)
        )
    }

    public static func write(_ value: PqcConfig, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.pinnedCertSha256, into: &buf)
        FfiConverterBool.write(value.enablePostQuantum, into: &buf)
        FfiConverterOptionUInt64.write(value.defaultTimeoutMs, into: &buf)
        FfiConverterOptionUInt64.write(value.connectTimeoutMs, into: &buf)
        FfiConverterOptionUInt64.write(value.maxBodyBytes, into: &buf)
        FfiConverterBool.write(value.enableCookies, into: &buf)
        FfiConverterOptionString.write(value.userAgent, into: &buf)
        FfiConverterTypeRedirectPolicy.write(value.redirectPolicy, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcConfig_lift(_ buf: RustBuffer) throws -> PqcConfig {
    return try FfiConverterTypePqcConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcConfig_lower(_ value: PqcConfig) -> RustBuffer {
    return FfiConverterTypePqcConfig.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum HttpMethod {
    
    case get
    case post
    case put
    case delete
    case patch
    case head
    case options
}


#if compiler(>=6)
extension HttpMethod: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpMethod: FfiConverterRustBuffer {
    typealias SwiftType = HttpMethod

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpMethod {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .get
        
        case 2: return .post
        
        case 3: return .put
        
        case 4: return .delete
        
        case 5: return .patch
        
        case 6: return .head
        
        case 7: return .options
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HttpMethod, into buf: inout [UInt8]) {
        switch value {
        
        
        case .get:
            writeInt(&buf, Int32(1))
        
        
        case .post:
            writeInt(&buf, Int32(2))
        
        
        case .put:
            writeInt(&buf, Int32(3))
        
        
        case .delete:
            writeInt(&buf, Int32(4))
        
        
        case .patch:
            writeInt(&buf, Int32(5))
        
        
        case .head:
            writeInt(&buf, Int32(6))
        
        
        case .options:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpMethod_lift(_ buf: RustBuffer) throws -> HttpMethod {
    return try FfiConverterTypeHttpMethod.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpMethod_lower(_ value: HttpMethod) -> RustBuffer {
    return FfiConverterTypeHttpMethod.lower(value)
}


extension HttpMethod: Equatable, Hashable {}







public enum PqcError: Swift.Error {

    
    
    case Network(message: String)
    
    case Tls(message: String)
    
    case Timeout(message: String)
    
    case InvalidRequest(message: String)
    
    case InvalidResponse(message: String)
    
    case PinningFailure(message: String)
    
    case TrustVerification(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePqcError: FfiConverterRustBuffer {
    typealias SwiftType = PqcError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PqcError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Tls(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Timeout(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidRequest(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .InvalidResponse(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .PinningFailure(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .TrustVerification(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PqcError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Tls(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Timeout(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidRequest(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .InvalidResponse(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .PinningFailure(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .TrustVerification(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcError_lift(_ buf: RustBuffer) throws -> PqcError {
    return try FfiConverterTypePqcError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcError_lower(_ value: PqcError) -> RustBuffer {
    return FfiConverterTypePqcError.lower(value)
}


extension PqcError: Equatable, Hashable {}




extension PqcError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * What the client does on a 3xx. The reqwest default (10 unbounded
 * redirects) is too permissive for a security-sensitive client. Variants
 * are struct-style (the `{}`) to preserve the generated binding shape.
 * `NoRedirects` (not `None`) avoids colliding with `Option::None` in matches.
 */

public enum RedirectPolicy {
    
    case noRedirects
    case sameOriginOnly
    case limited(max: UInt8
    )
}


#if compiler(>=6)
extension RedirectPolicy: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRedirectPolicy: FfiConverterRustBuffer {
    typealias SwiftType = RedirectPolicy

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RedirectPolicy {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .noRedirects
        
        case 2: return .sameOriginOnly
        
        case 3: return .limited(max: try FfiConverterUInt8.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RedirectPolicy, into buf: inout [UInt8]) {
        switch value {
        
        
        case .noRedirects:
            writeInt(&buf, Int32(1))
        
        
        case .sameOriginOnly:
            writeInt(&buf, Int32(2))
        
        
        case let .limited(max):
            writeInt(&buf, Int32(3))
            FfiConverterUInt8.write(max, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRedirectPolicy_lift(_ buf: RustBuffer) throws -> RedirectPolicy {
    return try FfiConverterTypeRedirectPolicy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRedirectPolicy_lower(_ value: RedirectPolicy) -> RustBuffer {
    return FfiConverterTypeRedirectPolicy.lower(value)
}


extension RedirectPolicy: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringSequenceString: FfiConverterRustBuffer {
    public static func write(_ value: [String: [String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterSequenceString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [String]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [String]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterSequenceString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePqcClientInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pqc_client_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqchttpclient_request() != 32508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_constructor_pqchttpclient_new() != 5152) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePqcClientInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all