// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pqcFFI)
import pqcFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pqc_client_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pqc_client_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePqcClientInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Foreign-implementable streaming upload body. The Rust client pulls
 * chunks via `next_chunk` until it returns `None` (EOF) or `Err`
 * (abort). Implemented by Kotlin and Swift to bridge OkHttp's
 * `RequestBody.writeTo(BufferedSink)` and `URLRequest.httpBodyStream`
 * (an `InputStream`) into Rust's `reqwest::Body::wrap_stream` without
 * buffering the full upload in memory — matching native OkHttp /
 * URLSession streaming-upload behavior.
 *
 * # Threading
 *
 * `next_chunk` is synchronous on the FFI surface. The Rust client
 * invokes it via `tokio::task::spawn_blocking` so the foreign call
 * doesn't park a tokio worker — implementers can block on local I/O
 * (file reads, okio.Pipe.source.read, InputStream.read) freely.
 *
 * # Chunk size
 *
 * Typical chunk size is 16-64 KiB. Smaller is fine (more FFI
 * round-trips); larger is fine (peak memory tracks the largest single
 * chunk). Returning an empty Vec is treated as EOF.
 *
 * # Retry safety
 *
 * Streaming bodies are NOT automatically retry-safe — once a chunk is
 * consumed it's gone (matches URLSession's `needNewBodyStream:`
 * contract). If a request needs retry, the consumer must construct a
 * fresh `BodyProvider`. Don't enable redirects on streaming uploads
 * unless the source can be re-read.
 */
public protocol BodyProvider: AnyObject, Sendable {
    
    /**
     * Return the next chunk of upload body, or `None` at EOF. Empty
     * vecs are also treated as EOF (lets callers signal end-of-stream
     * without keeping an Option flag).
     */
    func nextChunk() throws  -> Data?
    
    /**
     * Abort the upload and release foreign-side resources. Called by
     * the Rust client when the request errors before all chunks have
     * been pulled, when the caller drops the in-flight `PqcResponse`,
     * or when the request completes normally.
     *
     * Implementations must:
     * - Be idempotent (may be called multiple times).
     * - Be safe to call from any thread, including before
     * `next_chunk` has been invoked.
     * - Synchronously release I/O handles (e.g. close an
     * `okio.Pipe.source` to unblock the writer thread, close an
     * `InputStream`) — without this signal, a writer thread that
     * fills its pipe buffer would park forever on `sink.write()`
     * and the file descriptor / thread / buffer would leak per
     * aborted upload until process exit.
     */
    func cancel() 
    
}
/**
 * Foreign-implementable streaming upload body. The Rust client pulls
 * chunks via `next_chunk` until it returns `None` (EOF) or `Err`
 * (abort). Implemented by Kotlin and Swift to bridge OkHttp's
 * `RequestBody.writeTo(BufferedSink)` and `URLRequest.httpBodyStream`
 * (an `InputStream`) into Rust's `reqwest::Body::wrap_stream` without
 * buffering the full upload in memory — matching native OkHttp /
 * URLSession streaming-upload behavior.
 *
 * # Threading
 *
 * `next_chunk` is synchronous on the FFI surface. The Rust client
 * invokes it via `tokio::task::spawn_blocking` so the foreign call
 * doesn't park a tokio worker — implementers can block on local I/O
 * (file reads, okio.Pipe.source.read, InputStream.read) freely.
 *
 * # Chunk size
 *
 * Typical chunk size is 16-64 KiB. Smaller is fine (more FFI
 * round-trips); larger is fine (peak memory tracks the largest single
 * chunk). Returning an empty Vec is treated as EOF.
 *
 * # Retry safety
 *
 * Streaming bodies are NOT automatically retry-safe — once a chunk is
 * consumed it's gone (matches URLSession's `needNewBodyStream:`
 * contract). If a request needs retry, the consumer must construct a
 * fresh `BodyProvider`. Don't enable redirects on streaming uploads
 * unless the source can be re-read.
 */
open class BodyProviderImpl: BodyProvider, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pqc_client_fn_clone_bodyprovider(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pqc_client_fn_free_bodyprovider(pointer, $0) }
    }

    

    
    /**
     * Return the next chunk of upload body, or `None` at EOF. Empty
     * vecs are also treated as EOF (lets callers signal end-of-stream
     * without keeping an Option flag).
     */
open func nextChunk()throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypePqcError_lift) {
    uniffi_pqc_client_fn_method_bodyprovider_next_chunk(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Abort the upload and release foreign-side resources. Called by
     * the Rust client when the request errors before all chunks have
     * been pulled, when the caller drops the in-flight `PqcResponse`,
     * or when the request completes normally.
     *
     * Implementations must:
     * - Be idempotent (may be called multiple times).
     * - Be safe to call from any thread, including before
     * `next_chunk` has been invoked.
     * - Synchronously release I/O handles (e.g. close an
     * `okio.Pipe.source` to unblock the writer thread, close an
     * `InputStream`) — without this signal, a writer thread that
     * fills its pipe buffer would park forever on `sink.write()`
     * and the file descriptor / thread / buffer would leak per
     * aborted upload until process exit.
     */
open func cancel()  {try! rustCall() {
    uniffi_pqc_client_fn_method_bodyprovider_cancel(self.uniffiClonePointer(),$0
    )
}
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceBodyProvider {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceBodyProvider] = [UniffiVTableCallbackInterfaceBodyProvider(
        nextChunk: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data? in
                guard let uniffiObj = try? FfiConverterTypeBodyProvider.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.nextChunk(
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionData.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypePqcError_lower
            )
        },
        cancel: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeBodyProvider.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.cancel(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeBodyProvider.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface BodyProvider: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitBodyProvider() {
    uniffi_pqc_client_fn_init_callback_vtable_bodyprovider(UniffiCallbackInterfaceBodyProvider.vtable)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBodyProvider: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<BodyProvider>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = BodyProvider

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> BodyProvider {
        return BodyProviderImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: BodyProvider) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BodyProvider {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: BodyProvider, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBodyProvider_lift(_ pointer: UnsafeMutableRawPointer) throws -> BodyProvider {
    return try FfiConverterTypeBodyProvider.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBodyProvider_lower(_ value: BodyProvider) -> UnsafeMutableRawPointer {
    return FfiConverterTypeBodyProvider.lower(value)
}






/**
 * The HTTPS client exposed to Kotlin / Swift via UniFFI.
 *
 * Holds a single client with PQC TLS configured. Construct once per process
 * (it owns the connection pool); calling `request` is cheap.
 */
public protocol PqcHttpClientProtocol: AnyObject, Sendable {
    
    /**
     * Total bytes in the on-disk cache, for a "Clear cache (X MB)"
     * affordance. Returns `0` when caching is disabled or absent.
     */
    func cacheSizeBytes() async  -> UInt64
    
    /**
     * Clear all cached responses. Best-effort and non-throwing, mirroring
     * `URLCache.removeAllCachedResponses` / OkHttp `Cache.evictAll`. Also the
     * recommended logout / session-end hook so cached responses don't outlive
     * a session. A no-op when caching is disabled or the `cache` feature was
     * not compiled in.
     */
    func clearCache() async 
    
    func request(req: HttpRequest) async throws  -> PqcResponse
    
}
/**
 * The HTTPS client exposed to Kotlin / Swift via UniFFI.
 *
 * Holds a single client with PQC TLS configured. Construct once per process
 * (it owns the connection pool); calling `request` is cheap.
 */
open class PqcHttpClient: PqcHttpClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pqc_client_fn_clone_pqchttpclient(self.pointer, $0) }
    }
    /**
     * Returns `PqcError` (not panic) so consumers surface bad config —
     * e.g. malformed base64 in pinned_cert_sha256 — as a typed error.
     */
public convenience init(config: PqcConfig)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypePqcError_lift) {
    uniffi_pqc_client_fn_constructor_pqchttpclient_new(
        FfiConverterTypePqcConfig_lower(config),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pqc_client_fn_free_pqchttpclient(pointer, $0) }
    }

    

    
    /**
     * Total bytes in the on-disk cache, for a "Clear cache (X MB)"
     * affordance. Returns `0` when caching is disabled or absent.
     */
open func cacheSizeBytes()async  -> UInt64  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pqc_client_fn_method_pqchttpclient_cache_size_bytes(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_pqc_client_rust_future_poll_u64,
            completeFunc: ffi_pqc_client_rust_future_complete_u64,
            freeFunc: ffi_pqc_client_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Clear all cached responses. Best-effort and non-throwing, mirroring
     * `URLCache.removeAllCachedResponses` / OkHttp `Cache.evictAll`. Also the
     * recommended logout / session-end hook so cached responses don't outlive
     * a session. A no-op when caching is disabled or the `cache` feature was
     * not compiled in.
     */
open func clearCache()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pqc_client_fn_method_pqchttpclient_clear_cache(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_pqc_client_rust_future_poll_void,
            completeFunc: ffi_pqc_client_rust_future_complete_void,
            freeFunc: ffi_pqc_client_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
open func request(req: HttpRequest)async throws  -> PqcResponse  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pqc_client_fn_method_pqchttpclient_request(
                    self.uniffiClonePointer(),
                    FfiConverterTypeHttpRequest_lower(req)
                )
            },
            pollFunc: ffi_pqc_client_rust_future_poll_pointer,
            completeFunc: ffi_pqc_client_rust_future_complete_pointer,
            freeFunc: ffi_pqc_client_rust_future_free_pointer,
            liftFunc: FfiConverterTypePqcResponse_lift,
            errorHandler: FfiConverterTypePqcError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePqcHttpClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PqcHttpClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PqcHttpClient {
        return PqcHttpClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PqcHttpClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PqcHttpClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PqcHttpClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcHttpClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> PqcHttpClient {
    return try FfiConverterTypePqcHttpClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcHttpClient_lower(_ value: PqcHttpClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypePqcHttpClient.lower(value)
}






/**
 * Streaming HTTP response handle. Returned by [`PqcHttpClient::request`]
 * as soon as the response head (status, headers) has been received —
 * the body is pulled on demand via [`PqcResponse::read_chunk`] or
 * drained whole via [`PqcResponse::bytes`].
 *
 * Matches the streaming default of OkHttp's `ResponseBody` and
 * URLSession's `URLSession.bytes(for:)`. The buffered convenience
 * (`bytes()`) mirrors `body.bytes()` / `data(for:)`.
 *
 * # Concurrency
 *
 * `&self` methods can be called concurrently; an internal async mutex
 * serializes body reads. Only one reader at a time makes progress
 * (chunks have to come out in order), but headers/status are pre-
 * captured so those getters never block.
 *
 * # Lifecycle
 *
 * The connection (HTTP/2 stream or HTTP/1.1 socket) and the in-flight
 * semaphore permits acquired at request time both live inside this
 * object. Dropping the response without calling `bytes()` aborts the
 * body stream — same as OkHttp `Response.close()` and URLSession's
 * task-cancel semantics.
 *
 * # Cancellation note
 *
 * UniFFI 0.29 does not propagate foreign-runtime cancellation
 * (Swift `Task.cancel()`, Kotlin coroutine cancel) into Rust
 * (mozilla/uniffi-rs#2771). Consumers who want to abort an in-flight
 * body read must call [`PqcResponse::cancel`] explicitly — it's
 * synchronous, so iOS `URLProtocol.stopLoading` and OkHttp
 * `Source.close()` can call it without `Task { … }` or `runBlocking`.
 */
public protocol PqcResponseProtocol: AnyObject, Sendable {
    
    /**
     * Drain the entire body to a `Vec<u8>` (the buffered convenience,
     * mirroring OkHttp `body.bytes()` and URLSession `data(for:)`).
     * Internally consumes the response — subsequent `read_chunk`
     * calls return `Ok(None)`. Returns empty if `cancel()` has been
     * called.
     */
    func bytes() async throws  -> Data
    
    /**
     * Abort the body stream and release the underlying connection.
     * Idempotent — a second call is a no-op. Synchronous so iOS
     * `URLProtocol.stopLoading` and OkHttp `Source.close()` can call
     * it directly, without wrapping in `Task { … }` or `runBlocking`.
     *
     * If a `read_chunk`/`bytes` await is in flight when `cancel` is
     * called, the body mutex is contended and the in-flight chunk
     * completes normally; the post-await cancelled check then drops
     * the response and returns `Ok(None)` / empty bytes. This matches
     * OkHttp `Call.cancel()`, which also doesn't synchronously
     * interrupt a mid-read socket — interruption is best-effort.
     */
    func cancel() 
    
    /**
     * The URL the body actually came from, after any followed
     * redirects. Equals the request URL when no redirect occurred.
     * Lets callers detect a redirect they refused (see
     * `RedirectPolicy`) — mirrors OkHttp `Response.request().url()`
     * and `URLResponse.url`.
     */
    func finalUrl()  -> String
    
    /**
     * Response headers. Multi-valued headers (`Set-Cookie`, `Vary`,
     * `Link`) appear with all values intact — never collapsed.
     */
    func headers()  -> [String: [String]]
    
    /**
     * The negotiated ALPN protocol (`"h2"`, `"http/1.1"`, etc.).
     * Useful for logging / observability; the consumer never has to
     * branch on this.
     */
    func negotiatedProtocol()  -> String
    
    /**
     * Pull the next chunk of the body. Returns `Ok(None)` when the
     * body has been fully consumed (EOF) or `cancel()` has been
     * called. Chunks arrive in network order and are not bounded in
     * size — typically 16 KB to 64 KB for HTTP/2, larger for HTTP/1.1.
     */
    func readChunk() async throws  -> Data?
    
    /**
     * HTTP status code (e.g. 200, 404, 503).
     */
    func status()  -> UInt16
    
}
/**
 * Streaming HTTP response handle. Returned by [`PqcHttpClient::request`]
 * as soon as the response head (status, headers) has been received —
 * the body is pulled on demand via [`PqcResponse::read_chunk`] or
 * drained whole via [`PqcResponse::bytes`].
 *
 * Matches the streaming default of OkHttp's `ResponseBody` and
 * URLSession's `URLSession.bytes(for:)`. The buffered convenience
 * (`bytes()`) mirrors `body.bytes()` / `data(for:)`.
 *
 * # Concurrency
 *
 * `&self` methods can be called concurrently; an internal async mutex
 * serializes body reads. Only one reader at a time makes progress
 * (chunks have to come out in order), but headers/status are pre-
 * captured so those getters never block.
 *
 * # Lifecycle
 *
 * The connection (HTTP/2 stream or HTTP/1.1 socket) and the in-flight
 * semaphore permits acquired at request time both live inside this
 * object. Dropping the response without calling `bytes()` aborts the
 * body stream — same as OkHttp `Response.close()` and URLSession's
 * task-cancel semantics.
 *
 * # Cancellation note
 *
 * UniFFI 0.29 does not propagate foreign-runtime cancellation
 * (Swift `Task.cancel()`, Kotlin coroutine cancel) into Rust
 * (mozilla/uniffi-rs#2771). Consumers who want to abort an in-flight
 * body read must call [`PqcResponse::cancel`] explicitly — it's
 * synchronous, so iOS `URLProtocol.stopLoading` and OkHttp
 * `Source.close()` can call it without `Task { … }` or `runBlocking`.
 */
open class PqcResponse: PqcResponseProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_pqc_client_fn_clone_pqcresponse(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_pqc_client_fn_free_pqcresponse(pointer, $0) }
    }

    

    
    /**
     * Drain the entire body to a `Vec<u8>` (the buffered convenience,
     * mirroring OkHttp `body.bytes()` and URLSession `data(for:)`).
     * Internally consumes the response — subsequent `read_chunk`
     * calls return `Ok(None)`. Returns empty if `cancel()` has been
     * called.
     */
open func bytes()async throws  -> Data  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pqc_client_fn_method_pqcresponse_bytes(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_pqc_client_rust_future_poll_rust_buffer,
            completeFunc: ffi_pqc_client_rust_future_complete_rust_buffer,
            freeFunc: ffi_pqc_client_rust_future_free_rust_buffer,
            liftFunc: FfiConverterData.lift,
            errorHandler: FfiConverterTypePqcError_lift
        )
}
    
    /**
     * Abort the body stream and release the underlying connection.
     * Idempotent — a second call is a no-op. Synchronous so iOS
     * `URLProtocol.stopLoading` and OkHttp `Source.close()` can call
     * it directly, without wrapping in `Task { … }` or `runBlocking`.
     *
     * If a `read_chunk`/`bytes` await is in flight when `cancel` is
     * called, the body mutex is contended and the in-flight chunk
     * completes normally; the post-await cancelled check then drops
     * the response and returns `Ok(None)` / empty bytes. This matches
     * OkHttp `Call.cancel()`, which also doesn't synchronously
     * interrupt a mid-read socket — interruption is best-effort.
     */
open func cancel()  {try! rustCall() {
    uniffi_pqc_client_fn_method_pqcresponse_cancel(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * The URL the body actually came from, after any followed
     * redirects. Equals the request URL when no redirect occurred.
     * Lets callers detect a redirect they refused (see
     * `RedirectPolicy`) — mirrors OkHttp `Response.request().url()`
     * and `URLResponse.url`.
     */
open func finalUrl() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_pqc_client_fn_method_pqcresponse_final_url(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Response headers. Multi-valued headers (`Set-Cookie`, `Vary`,
     * `Link`) appear with all values intact — never collapsed.
     */
open func headers() -> [String: [String]]  {
    return try!  FfiConverterDictionaryStringSequenceString.lift(try! rustCall() {
    uniffi_pqc_client_fn_method_pqcresponse_headers(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * The negotiated ALPN protocol (`"h2"`, `"http/1.1"`, etc.).
     * Useful for logging / observability; the consumer never has to
     * branch on this.
     */
open func negotiatedProtocol() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_pqc_client_fn_method_pqcresponse_negotiated_protocol(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Pull the next chunk of the body. Returns `Ok(None)` when the
     * body has been fully consumed (EOF) or `cancel()` has been
     * called. Chunks arrive in network order and are not bounded in
     * size — typically 16 KB to 64 KB for HTTP/2, larger for HTTP/1.1.
     */
open func readChunk()async throws  -> Data?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_pqc_client_fn_method_pqcresponse_read_chunk(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_pqc_client_rust_future_poll_rust_buffer,
            completeFunc: ffi_pqc_client_rust_future_complete_rust_buffer,
            freeFunc: ffi_pqc_client_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionData.lift,
            errorHandler: FfiConverterTypePqcError_lift
        )
}
    
    /**
     * HTTP status code (e.g. 200, 404, 503).
     */
open func status() -> UInt16  {
    return try!  FfiConverterUInt16.lift(try! rustCall() {
    uniffi_pqc_client_fn_method_pqcresponse_status(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePqcResponse: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PqcResponse

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PqcResponse {
        return PqcResponse(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PqcResponse) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PqcResponse {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PqcResponse, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcResponse_lift(_ pointer: UnsafeMutableRawPointer) throws -> PqcResponse {
    return try FfiConverterTypePqcResponse.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcResponse_lower(_ value: PqcResponse) -> UnsafeMutableRawPointer {
    return FfiConverterTypePqcResponse.lower(value)
}




public struct HttpRequest {
    public var method: HttpMethod
    public var url: String
    public var headers: [String: [String]]
    /**
     * Inline body bytes for small uploads (request payload fully in
     * memory). Mutually exclusive with `body_stream`; passing both is
     * rejected with `PqcError::InvalidRequest`.
     */
    public var body: Data?
    /**
     * Streaming upload body. When set, the client pulls chunks from
     * the provider and forwards them to the server without buffering
     * the full payload — required for large file uploads on
     * memory-constrained devices. Mutually exclusive with `body`.
     */
    public var bodyStream: BodyProvider?
    /**
     * Optional `Content-Length` hint when using `body_stream`. When
     * `None`, the request uses chunked transfer-encoding (the natural
     * fit for stream sources of unknown length); when `Some(n)`, the
     * `Content-Length: n` header is set and the server gets a
     * content-length-framed body. Set this when the source's total
     * size is known (file uploads); leave `None` for live streams.
     */
    public var bodyStreamLength: UInt64?
    public var timeoutMs: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(method: HttpMethod, url: String, headers: [String: [String]], 
        /**
         * Inline body bytes for small uploads (request payload fully in
         * memory). Mutually exclusive with `body_stream`; passing both is
         * rejected with `PqcError::InvalidRequest`.
         */body: Data?, 
        /**
         * Streaming upload body. When set, the client pulls chunks from
         * the provider and forwards them to the server without buffering
         * the full payload — required for large file uploads on
         * memory-constrained devices. Mutually exclusive with `body`.
         */bodyStream: BodyProvider? = nil, 
        /**
         * Optional `Content-Length` hint when using `body_stream`. When
         * `None`, the request uses chunked transfer-encoding (the natural
         * fit for stream sources of unknown length); when `Some(n)`, the
         * `Content-Length: n` header is set and the server gets a
         * content-length-framed body. Set this when the source's total
         * size is known (file uploads); leave `None` for live streams.
         */bodyStreamLength: UInt64? = nil, timeoutMs: UInt64?) {
        self.method = method
        self.url = url
        self.headers = headers
        self.body = body
        self.bodyStream = bodyStream
        self.bodyStreamLength = bodyStreamLength
        self.timeoutMs = timeoutMs
    }
}

#if compiler(>=6)
extension HttpRequest: Sendable {}
#endif



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpRequest {
        return
            try HttpRequest(
                method: FfiConverterTypeHttpMethod.read(from: &buf), 
                url: FfiConverterString.read(from: &buf), 
                headers: FfiConverterDictionaryStringSequenceString.read(from: &buf), 
                body: FfiConverterOptionData.read(from: &buf), 
                bodyStream: FfiConverterOptionTypeBodyProvider.read(from: &buf), 
                bodyStreamLength: FfiConverterOptionUInt64.read(from: &buf), 
                timeoutMs: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HttpRequest, into buf: inout [UInt8]) {
        FfiConverterTypeHttpMethod.write(value.method, into: &buf)
        FfiConverterString.write(value.url, into: &buf)
        FfiConverterDictionaryStringSequenceString.write(value.headers, into: &buf)
        FfiConverterOptionData.write(value.body, into: &buf)
        FfiConverterOptionTypeBodyProvider.write(value.bodyStream, into: &buf)
        FfiConverterOptionUInt64.write(value.bodyStreamLength, into: &buf)
        FfiConverterOptionUInt64.write(value.timeoutMs, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lift(_ buf: RustBuffer) throws -> HttpRequest {
    return try FfiConverterTypeHttpRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpRequest_lower(_ value: HttpRequest) -> RustBuffer {
    return FfiConverterTypeHttpRequest.lower(value)
}


/**
 * Configuration handed to `PqcHttpClient::new`. Defaults are tuned for
 * mobile and safe to set from Swift/Kotlin without reading the docs.
 * All `*_ms` fields are milliseconds.
 */
public struct PqcConfig {
    /**
     * Base64 SHA-256 of a DER SPKI (standard or URL-safe) the client will
     * accept. Matches if ANY cert in the chain — leaf or intermediate —
     * has a matching SPKI hash (the leaf must still parse); empty disables
     * pinning. Pin the issuing intermediate CA, keep >= 2 pins, never pin a
     * public root. See `src/pinning.rs`.
     */
    public var pinnedCertSha256: [String]
    /**
     * Total request budget (handshake + headers + body); on expiry the
     * request aborts with `PqcError::Timeout`. `None` means no total cap —
     * discouraged for mobile.
     */
    public var defaultTimeoutMs: UInt64?
    /**
     * TCP-connect / TLS-handshake budget, capped separately from
     * `default_timeout_ms` so a stalled connect (e.g. cellular handover)
     * fails fast instead of burning the whole request budget. `None` = 10s.
     */
    public var connectTimeoutMs: UInt64?
    /**
     * Idle timeout between body-bytes read operations. The timer resets
     * after every successful chunk read, so a healthy slow download is
     * not killed by it; only a stalled server (TCP open but no bytes
     * flowing) is. Mirrors OkHttp's `readTimeout`.
     *
     * `None` (default) leaves this off — only `default_timeout_ms` (the
     * total request budget) applies. Set this when downloading large
     * bodies where you'd rather kill a stuck stream within seconds than
     * wait for the total budget to expire (recommended values: 10–30s for
     * APIs, 60s+ for large file downloads).
     */
    public var readIdleTimeoutMs: UInt64?
    /**
     * Off by default: no cookie jar, so callers round-trip
     * `Set-Cookie`/`Cookie` themselves. Auto-attaching cookies across
     * endpoints is a session-leak vector — enable only when needed.
     */
    public var enableCookies: Bool
    /**
     * Sent verbatim as `User-Agent`. `None` uses reqwest's default, which
     * many WAFs (Akamai Bot Manager, bank UA allowlists) reject — set your
     * app's identifier.
     */
    public var userAgent: String?
    /**
     * Which DNS resolver to use. `None` (default) selects `System` —
     * libc `getaddrinfo` driven on tokio's blocking pool, which on
     * Android honors user-configured Private DNS (DNS-over-TLS) and on
     * iOS honors the system resolver chain.
     *
     * Set to `Some(Hickory)` to use the bundled hickory-dns async
     * resolver, which enables RFC 8305 Happy Eyeballs (concurrent
     * v4/v6 connection racing — meaningfully faster on dual-stack
     * networks where one family is broken). The trade-off: hickory
     * bypasses Android's Private DNS setting, so consumers whose users
     * depend on DoT for privacy/policy should leave this at `None`.
     */
    public var dnsResolver: DnsResolver?
    /**
     * How to handle 3xx. Default `SameOriginOnly` — cross-origin redirects
     * are refused so a redirect can't silently downgrade to an un-pinned
     * host.
     *
     * "Refused" here follows reqwest semantics: the redirect is **not
     * followed**, and the 3xx response itself (with its `Location` header) is
     * returned to the caller — it is *not* turned into an error. Callers that
     * treat any `status < 400` as success should therefore check for 3xx, or
     * read `final_url` on the response to confirm where the body came from.
     */
    public var redirectPolicy: RedirectPolicy
    /**
     * Maximum concurrent in-flight requests across all hosts. Acquired
     * before cache lookup and network send, so cache hits also count
     * against the budget — matches OkHttp's `Dispatcher.maxRequests`.
     * Default 64 mirrors OkHttp; `Some(n)` enforces n; `None` disables the
     * global gate entirely (use only when a consumer needs unbounded
     * concurrency, e.g. server-side or tunnelled use).
     */
    public var maxInflightTotal: UInt32?
    /**
     * Maximum concurrent in-flight requests per host, keyed by URL hostname
     * (no port, no scheme). Default 5 mirrors OkHttp's
     * `Dispatcher.maxRequestsPerHost`. URLSession's analogous cap is 6
     * in-flight per host; we pick the lower OkHttp value. `None` disables
     * the per-host gate.
     *
     * Once a host is seen for the first time, its semaphore lives for the
     * lifetime of the client (one entry per unique host). For a typical
     * mobile app this is bounded by the number of distinct API hosts the
     * app talks to (usually under 100); the memory cost is negligible.
     */
    public var maxInflightPerHost: UInt32?
    /**
     * Opt-in RFC 9111 response cache (default false). When enabled it mirrors
     * the platform HTTP caches (Android OkHttp `Cache`, iOS `URLCache`):
     * cacheability is decided by request method + response status + cache
     * headers (`Cache-Control`, `ETag`, `Last-Modified`, `Vary`, …), never by
     * file type / `Content-Type`. A private cache (`shared = false`), so it
     * honors `no-store`/`no-cache` but — like the native private caches —
     * will cache responses to `Authorization`-bearing requests when their
     * headers permit; suppress those by having the server send `no-store`.
     *
     * Only effective in builds compiled with the `cache` cargo feature; in a
     * feature-less build this is a no-op (and `clear_cache`/`cache_size_bytes`
     * are inert). See `src/cache.rs`.
     */
    public var enableCache: Bool
    /**
     * Directory for the persistent on-disk cache tier (present on both
     * platforms, matching OkHttp's `Cache` directory and `URLCache`'s disk
     * store). Pass an app-writable path — Android `context.cacheDir`, iOS the
     * `.cachesDirectory`. `None` disables the disk tier; the cache then lives
     * only in the in-memory tier where one exists (iOS), or is effectively
     * disabled (Android). Ignored when `enable_cache` is false.
     */
    public var cacheDir: String?
    /**
     * Hard ceiling on the on-disk cache in bytes. When exceeded, the oldest
     * entries are evicted to stay under it (cf. OkHttp's `maxSize`). `None`
     * defaults to 20 MiB, matching a typical `URLCache` disk capacity.
     */
    public var maxCacheBytes: UInt64?
    /**
     * Hard ceiling on the in-process LRU memory cache tier, in bytes.
     * `None` defaults to 4 MiB on both platforms (matching `URLCache`'s
     * historical memory capacity). `Some(0)` opts out of the memory tier
     * entirely — Android consumers who want OkHttp-style disk-only
     * behavior set this to `Some(0)`.
     *
     * Native baseline note: OkHttp's bundled `Cache` is disk-only (the
     * `Cache` class is `final` and not extensible), so OkHttp users get
     * no HTTP memory cache out of the box. URLCache on iOS does have a
     * memory tier. We expose the same tier on both platforms because
     * modern Android ART has dynamic heaps and the historical Dalvik
     * caps that drove OkHttp's choice no longer apply.
     */
    public var maxMemoryCacheBytes: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Base64 SHA-256 of a DER SPKI (standard or URL-safe) the client will
         * accept. Matches if ANY cert in the chain — leaf or intermediate —
         * has a matching SPKI hash (the leaf must still parse); empty disables
         * pinning. Pin the issuing intermediate CA, keep >= 2 pins, never pin a
         * public root. See `src/pinning.rs`.
         */pinnedCertSha256: [String], 
        /**
         * Total request budget (handshake + headers + body); on expiry the
         * request aborts with `PqcError::Timeout`. `None` means no total cap —
         * discouraged for mobile.
         */defaultTimeoutMs: UInt64?, 
        /**
         * TCP-connect / TLS-handshake budget, capped separately from
         * `default_timeout_ms` so a stalled connect (e.g. cellular handover)
         * fails fast instead of burning the whole request budget. `None` = 10s.
         */connectTimeoutMs: UInt64?, 
        /**
         * Idle timeout between body-bytes read operations. The timer resets
         * after every successful chunk read, so a healthy slow download is
         * not killed by it; only a stalled server (TCP open but no bytes
         * flowing) is. Mirrors OkHttp's `readTimeout`.
         *
         * `None` (default) leaves this off — only `default_timeout_ms` (the
         * total request budget) applies. Set this when downloading large
         * bodies where you'd rather kill a stuck stream within seconds than
         * wait for the total budget to expire (recommended values: 10–30s for
         * APIs, 60s+ for large file downloads).
         */readIdleTimeoutMs: UInt64? = nil, 
        /**
         * Off by default: no cookie jar, so callers round-trip
         * `Set-Cookie`/`Cookie` themselves. Auto-attaching cookies across
         * endpoints is a session-leak vector — enable only when needed.
         */enableCookies: Bool, 
        /**
         * Sent verbatim as `User-Agent`. `None` uses reqwest's default, which
         * many WAFs (Akamai Bot Manager, bank UA allowlists) reject — set your
         * app's identifier.
         */userAgent: String?, 
        /**
         * Which DNS resolver to use. `None` (default) selects `System` —
         * libc `getaddrinfo` driven on tokio's blocking pool, which on
         * Android honors user-configured Private DNS (DNS-over-TLS) and on
         * iOS honors the system resolver chain.
         *
         * Set to `Some(Hickory)` to use the bundled hickory-dns async
         * resolver, which enables RFC 8305 Happy Eyeballs (concurrent
         * v4/v6 connection racing — meaningfully faster on dual-stack
         * networks where one family is broken). The trade-off: hickory
         * bypasses Android's Private DNS setting, so consumers whose users
         * depend on DoT for privacy/policy should leave this at `None`.
         */dnsResolver: DnsResolver? = nil, 
        /**
         * How to handle 3xx. Default `SameOriginOnly` — cross-origin redirects
         * are refused so a redirect can't silently downgrade to an un-pinned
         * host.
         *
         * "Refused" here follows reqwest semantics: the redirect is **not
         * followed**, and the 3xx response itself (with its `Location` header) is
         * returned to the caller — it is *not* turned into an error. Callers that
         * treat any `status < 400` as success should therefore check for 3xx, or
         * read `final_url` on the response to confirm where the body came from.
         */redirectPolicy: RedirectPolicy, 
        /**
         * Maximum concurrent in-flight requests across all hosts. Acquired
         * before cache lookup and network send, so cache hits also count
         * against the budget — matches OkHttp's `Dispatcher.maxRequests`.
         * Default 64 mirrors OkHttp; `Some(n)` enforces n; `None` disables the
         * global gate entirely (use only when a consumer needs unbounded
         * concurrency, e.g. server-side or tunnelled use).
         */maxInflightTotal: UInt32? = UInt32(64), 
        /**
         * Maximum concurrent in-flight requests per host, keyed by URL hostname
         * (no port, no scheme). Default 5 mirrors OkHttp's
         * `Dispatcher.maxRequestsPerHost`. URLSession's analogous cap is 6
         * in-flight per host; we pick the lower OkHttp value. `None` disables
         * the per-host gate.
         *
         * Once a host is seen for the first time, its semaphore lives for the
         * lifetime of the client (one entry per unique host). For a typical
         * mobile app this is bounded by the number of distinct API hosts the
         * app talks to (usually under 100); the memory cost is negligible.
         */maxInflightPerHost: UInt32? = UInt32(5), 
        /**
         * Opt-in RFC 9111 response cache (default false). When enabled it mirrors
         * the platform HTTP caches (Android OkHttp `Cache`, iOS `URLCache`):
         * cacheability is decided by request method + response status + cache
         * headers (`Cache-Control`, `ETag`, `Last-Modified`, `Vary`, …), never by
         * file type / `Content-Type`. A private cache (`shared = false`), so it
         * honors `no-store`/`no-cache` but — like the native private caches —
         * will cache responses to `Authorization`-bearing requests when their
         * headers permit; suppress those by having the server send `no-store`.
         *
         * Only effective in builds compiled with the `cache` cargo feature; in a
         * feature-less build this is a no-op (and `clear_cache`/`cache_size_bytes`
         * are inert). See `src/cache.rs`.
         */enableCache: Bool = false, 
        /**
         * Directory for the persistent on-disk cache tier (present on both
         * platforms, matching OkHttp's `Cache` directory and `URLCache`'s disk
         * store). Pass an app-writable path — Android `context.cacheDir`, iOS the
         * `.cachesDirectory`. `None` disables the disk tier; the cache then lives
         * only in the in-memory tier where one exists (iOS), or is effectively
         * disabled (Android). Ignored when `enable_cache` is false.
         */cacheDir: String? = nil, 
        /**
         * Hard ceiling on the on-disk cache in bytes. When exceeded, the oldest
         * entries are evicted to stay under it (cf. OkHttp's `maxSize`). `None`
         * defaults to 20 MiB, matching a typical `URLCache` disk capacity.
         */maxCacheBytes: UInt64? = nil, 
        /**
         * Hard ceiling on the in-process LRU memory cache tier, in bytes.
         * `None` defaults to 4 MiB on both platforms (matching `URLCache`'s
         * historical memory capacity). `Some(0)` opts out of the memory tier
         * entirely — Android consumers who want OkHttp-style disk-only
         * behavior set this to `Some(0)`.
         *
         * Native baseline note: OkHttp's bundled `Cache` is disk-only (the
         * `Cache` class is `final` and not extensible), so OkHttp users get
         * no HTTP memory cache out of the box. URLCache on iOS does have a
         * memory tier. We expose the same tier on both platforms because
         * modern Android ART has dynamic heaps and the historical Dalvik
         * caps that drove OkHttp's choice no longer apply.
         */maxMemoryCacheBytes: UInt64? = nil) {
        self.pinnedCertSha256 = pinnedCertSha256
        self.defaultTimeoutMs = defaultTimeoutMs
        self.connectTimeoutMs = connectTimeoutMs
        self.readIdleTimeoutMs = readIdleTimeoutMs
        self.enableCookies = enableCookies
        self.userAgent = userAgent
        self.dnsResolver = dnsResolver
        self.redirectPolicy = redirectPolicy
        self.maxInflightTotal = maxInflightTotal
        self.maxInflightPerHost = maxInflightPerHost
        self.enableCache = enableCache
        self.cacheDir = cacheDir
        self.maxCacheBytes = maxCacheBytes
        self.maxMemoryCacheBytes = maxMemoryCacheBytes
    }
}

#if compiler(>=6)
extension PqcConfig: Sendable {}
#endif


extension PqcConfig: Equatable, Hashable {
    public static func ==(lhs: PqcConfig, rhs: PqcConfig) -> Bool {
        if lhs.pinnedCertSha256 != rhs.pinnedCertSha256 {
            return false
        }
        if lhs.defaultTimeoutMs != rhs.defaultTimeoutMs {
            return false
        }
        if lhs.connectTimeoutMs != rhs.connectTimeoutMs {
            return false
        }
        if lhs.readIdleTimeoutMs != rhs.readIdleTimeoutMs {
            return false
        }
        if lhs.enableCookies != rhs.enableCookies {
            return false
        }
        if lhs.userAgent != rhs.userAgent {
            return false
        }
        if lhs.dnsResolver != rhs.dnsResolver {
            return false
        }
        if lhs.redirectPolicy != rhs.redirectPolicy {
            return false
        }
        if lhs.maxInflightTotal != rhs.maxInflightTotal {
            return false
        }
        if lhs.maxInflightPerHost != rhs.maxInflightPerHost {
            return false
        }
        if lhs.enableCache != rhs.enableCache {
            return false
        }
        if lhs.cacheDir != rhs.cacheDir {
            return false
        }
        if lhs.maxCacheBytes != rhs.maxCacheBytes {
            return false
        }
        if lhs.maxMemoryCacheBytes != rhs.maxMemoryCacheBytes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(pinnedCertSha256)
        hasher.combine(defaultTimeoutMs)
        hasher.combine(connectTimeoutMs)
        hasher.combine(readIdleTimeoutMs)
        hasher.combine(enableCookies)
        hasher.combine(userAgent)
        hasher.combine(dnsResolver)
        hasher.combine(redirectPolicy)
        hasher.combine(maxInflightTotal)
        hasher.combine(maxInflightPerHost)
        hasher.combine(enableCache)
        hasher.combine(cacheDir)
        hasher.combine(maxCacheBytes)
        hasher.combine(maxMemoryCacheBytes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePqcConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PqcConfig {
        return
            try PqcConfig(
                pinnedCertSha256: FfiConverterSequenceString.read(from: &buf), 
                defaultTimeoutMs: FfiConverterOptionUInt64.read(from: &buf), 
                connectTimeoutMs: FfiConverterOptionUInt64.read(from: &buf), 
                readIdleTimeoutMs: FfiConverterOptionUInt64.read(from: &buf), 
                enableCookies: FfiConverterBool.read(from: &buf), 
                userAgent: FfiConverterOptionString.read(from: &buf), 
                dnsResolver: FfiConverterOptionTypeDnsResolver.read(from: &buf), 
                redirectPolicy: FfiConverterTypeRedirectPolicy.read(from: &buf), 
                maxInflightTotal: FfiConverterOptionUInt32.read(from: &buf), 
                maxInflightPerHost: FfiConverterOptionUInt32.read(from: &buf), 
                enableCache: FfiConverterBool.read(from: &buf), 
                cacheDir: FfiConverterOptionString.read(from: &buf), 
                maxCacheBytes: FfiConverterOptionUInt64.read(from: &buf), 
                maxMemoryCacheBytes: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: PqcConfig, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.pinnedCertSha256, into: &buf)
        FfiConverterOptionUInt64.write(value.defaultTimeoutMs, into: &buf)
        FfiConverterOptionUInt64.write(value.connectTimeoutMs, into: &buf)
        FfiConverterOptionUInt64.write(value.readIdleTimeoutMs, into: &buf)
        FfiConverterBool.write(value.enableCookies, into: &buf)
        FfiConverterOptionString.write(value.userAgent, into: &buf)
        FfiConverterOptionTypeDnsResolver.write(value.dnsResolver, into: &buf)
        FfiConverterTypeRedirectPolicy.write(value.redirectPolicy, into: &buf)
        FfiConverterOptionUInt32.write(value.maxInflightTotal, into: &buf)
        FfiConverterOptionUInt32.write(value.maxInflightPerHost, into: &buf)
        FfiConverterBool.write(value.enableCache, into: &buf)
        FfiConverterOptionString.write(value.cacheDir, into: &buf)
        FfiConverterOptionUInt64.write(value.maxCacheBytes, into: &buf)
        FfiConverterOptionUInt64.write(value.maxMemoryCacheBytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcConfig_lift(_ buf: RustBuffer) throws -> PqcConfig {
    return try FfiConverterTypePqcConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcConfig_lower(_ value: PqcConfig) -> RustBuffer {
    return FfiConverterTypePqcConfig.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * DNS resolver selection. See `PqcConfig::dns_resolver` for the full
 * trade-off (Happy Eyeballs vs. Android Private DNS interaction).
 */

public enum DnsResolver {
    
    /**
     * libc `getaddrinfo` (synchronous, on tokio's blocking pool).
     * Honors Android Private DNS / DoT and the iOS system resolver chain.
     */
    case system
    /**
     * hickory-resolver (async, RFC 8305 Happy Eyeballs). Bypasses
     * Android Private DNS.
     */
    case hickory
}


#if compiler(>=6)
extension DnsResolver: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDnsResolver: FfiConverterRustBuffer {
    typealias SwiftType = DnsResolver

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DnsResolver {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .system
        
        case 2: return .hickory
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DnsResolver, into buf: inout [UInt8]) {
        switch value {
        
        
        case .system:
            writeInt(&buf, Int32(1))
        
        
        case .hickory:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDnsResolver_lift(_ buf: RustBuffer) throws -> DnsResolver {
    return try FfiConverterTypeDnsResolver.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDnsResolver_lower(_ value: DnsResolver) -> RustBuffer {
    return FfiConverterTypeDnsResolver.lower(value)
}


extension DnsResolver: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum HttpMethod {
    
    case get
    case post
    case put
    case delete
    case patch
    case head
    case options
}


#if compiler(>=6)
extension HttpMethod: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHttpMethod: FfiConverterRustBuffer {
    typealias SwiftType = HttpMethod

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HttpMethod {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .get
        
        case 2: return .post
        
        case 3: return .put
        
        case 4: return .delete
        
        case 5: return .patch
        
        case 6: return .head
        
        case 7: return .options
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HttpMethod, into buf: inout [UInt8]) {
        switch value {
        
        
        case .get:
            writeInt(&buf, Int32(1))
        
        
        case .post:
            writeInt(&buf, Int32(2))
        
        
        case .put:
            writeInt(&buf, Int32(3))
        
        
        case .delete:
            writeInt(&buf, Int32(4))
        
        
        case .patch:
            writeInt(&buf, Int32(5))
        
        
        case .head:
            writeInt(&buf, Int32(6))
        
        
        case .options:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpMethod_lift(_ buf: RustBuffer) throws -> HttpMethod {
    return try FfiConverterTypeHttpMethod.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHttpMethod_lower(_ value: HttpMethod) -> RustBuffer {
    return FfiConverterTypeHttpMethod.lower(value)
}


extension HttpMethod: Equatable, Hashable {}







public enum PqcError: Swift.Error {

    
    
    case Network(message: String)
    
    case Tls(message: String)
    
    case Timeout(message: String)
    
    case InvalidRequest(message: String)
    
    case PinningFailure(message: String)
    
    case TrustVerification(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePqcError: FfiConverterRustBuffer {
    typealias SwiftType = PqcError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PqcError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Network(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .Tls(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .Timeout(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .InvalidRequest(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .PinningFailure(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .TrustVerification(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PqcError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Network(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .Tls(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .Timeout(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .InvalidRequest(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .PinningFailure(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .TrustVerification(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcError_lift(_ buf: RustBuffer) throws -> PqcError {
    return try FfiConverterTypePqcError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePqcError_lower(_ value: PqcError) -> RustBuffer {
    return FfiConverterTypePqcError.lower(value)
}


extension PqcError: Equatable, Hashable {}




extension PqcError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * What the client does on a 3xx. The reqwest default (10 unbounded
 * redirects) is too permissive for a security-sensitive client. Variants
 * are struct-style (the `{}`) to preserve the generated binding shape.
 * `NoRedirects` (not `None`) avoids colliding with `Option::None` in matches.
 */

public enum RedirectPolicy {
    
    case noRedirects
    case sameOriginOnly
    case limited(max: UInt8
    )
}


#if compiler(>=6)
extension RedirectPolicy: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRedirectPolicy: FfiConverterRustBuffer {
    typealias SwiftType = RedirectPolicy

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RedirectPolicy {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .noRedirects
        
        case 2: return .sameOriginOnly
        
        case 3: return .limited(max: try FfiConverterUInt8.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RedirectPolicy, into buf: inout [UInt8]) {
        switch value {
        
        
        case .noRedirects:
            writeInt(&buf, Int32(1))
        
        
        case .sameOriginOnly:
            writeInt(&buf, Int32(2))
        
        
        case let .limited(max):
            writeInt(&buf, Int32(3))
            FfiConverterUInt8.write(max, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRedirectPolicy_lift(_ buf: RustBuffer) throws -> RedirectPolicy {
    return try FfiConverterTypeRedirectPolicy.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRedirectPolicy_lower(_ value: RedirectPolicy) -> RustBuffer {
    return FfiConverterTypeRedirectPolicy.lower(value)
}


extension RedirectPolicy: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeBodyProvider: FfiConverterRustBuffer {
    typealias SwiftType = BodyProvider?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeBodyProvider.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeBodyProvider.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDnsResolver: FfiConverterRustBuffer {
    typealias SwiftType = DnsResolver?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDnsResolver.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDnsResolver.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDictionaryStringSequenceString: FfiConverterRustBuffer {
    public static func write(_ value: [String: [String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterSequenceString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: [String]] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: [String]]()
        dict.reserveCapacity(Int(len))
        for _ in 0..<len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterSequenceString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsurePqcClientInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pqc_client_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pqc_client_checksum_method_bodyprovider_next_chunk() != 25415) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_bodyprovider_cancel() != 10343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqchttpclient_cache_size_bytes() != 50194) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqchttpclient_clear_cache() != 43165) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqchttpclient_request() != 18885) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqcresponse_bytes() != 45301) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqcresponse_cancel() != 11085) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqcresponse_final_url() != 10476) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqcresponse_headers() != 116) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqcresponse_negotiated_protocol() != 18904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqcresponse_read_chunk() != 48167) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_method_pqcresponse_status() != 16651) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pqc_client_checksum_constructor_pqchttpclient_new() != 5152) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitBodyProvider()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePqcClientInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all